version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: notice-mongo
    ports:
      - "127.0.0.1:27017:27017"

  app:
    build: .
    env_file:
      - .env
    container_name: notice-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/noticebot